blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Discussions & Questions
    url: https://github.com/SerSamD/Project/discussions
    about: Posez des questions ou discutez avec la communautÃ©
  - name: ğŸ” Signaler une VulnÃ©rabilitÃ© de SÃ©curitÃ©
    url: https://github.com/SerSamD/Project/security/advisories/new
    about: Signalez des problÃ¨mes de sÃ©curitÃ© de maniÃ¨re confidentielle
